### ISSUE TITLE
Large variables cause varInspector to slow down entire notebook.

### ISSUE THREAD

**Issue by H0bbitBaron** [jfbercher/jupyter_varInspector#4]
Hi, as mentioned in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1275 large variables hangs notebook. Is there possibility to toggle SIZE column in inspector to disable size recalculation?

**Comment by G-u-i-l-l-e** [comment]
Not sure if it helps, but modifying the file var_list.r (var_list.py for Python kernel) you can show other information about the variable. For instance, the following code shows the dimensions of the variable instead of the size (changes over the original code in bold face):

library(jsonlite)
**_dimen <- function(x){ifelse(is.vector(x),return(length(x)),return(dim(x)))}_**
var_dic_list = function(){ 
    ll = ls(.GlobalEnv, all.names = FALSE)
    varList=list()
    iter = 1
        for (k in ll){
            if (class(get(k))!='function'){
            class = class(get(k)); rk = capture.output(str(get(k))); **_size =  dimen(get(k))_**; sk = substr(get(k),0, 200); 
            #  [{'varName':v, 'varType': type(eval(v)).__name__, 'varSize': _getsizeof(eval(v)), 'varContent': str(eval(v))[:200]} 
            l = list(varName = k, varType = class, varSize = size, varContent = sk)
            varList[[iter]] = l
            # print(l)
            iter = iter + 1}
        }
return(toJSON(varList, simplifyVector = FALSE, force=TRUE))
    }
cat(var_dic_list())
